import React from "react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "../ui/dialog"

type TermsAndConditionsProps = {
  onAccept: () => void
  modalOpenStatus: boolean
}

const TermsAndConditions = ({
  onAccept,
  modalOpenStatus,
}: TermsAndConditionsProps) => {
  return (
    <Dialog open={modalOpenStatus}>
      <DialogContent className="overflow-scroll max-h-[80vh] w-[70vw] max-w-[1000px]">
        <DialogHeader>
          <DialogTitle>
            <h1 className="text-2xl">
              Terms and Conditions for OpSec Cloudverse
            </h1>
          </DialogTitle>
          <DialogDescription>
            <div>
              <div className="pb-10 leading-8">
                <p>
                  <strong className="text-white">Introduction</strong>
                </p>
                <p>
                  Welcome to OpSec Cloudverse! By accessing our platform, you
                  agree to these Terms and Conditions, designed to ensure a
                  clear understanding of the rules and your obligations when
                  using our services. Please read these terms carefully before
                  using the platform.
                </p>

                <h2 className="text-white">1. Definitions</h2>
                <p>
                  <strong>&quot;Node&quot;</strong> refers to blockchain nodes
                  available for deployment via the OpSec platform, which
                  supports various blockchain networks.
                </p>
                <p>
                  <strong>&quot;Services&quot;</strong> include, but are not
                  limited to, the provision of GPUs, VPS solutions, validator
                  services, and access to computational resources.
                </p>
                <p>
                  <strong>&quot;Credits&quot;</strong> are the currency used
                  within the OpSec platform, purchased with ETH, for subscribing
                  to Nodes.
                </p>

                <h2 className="text-white">2. General Use</h2>
                <p>
                  Users must register for an account to access Nodes and
                  Services. By registering, you agree to provide accurate and
                  complete information and to keep this information up to date.
                </p>
                <p>
                  OpSec grants you a limited, non-exclusive, non-transferable,
                  and revocable license to use the Services according to these
                  Terms.
                </p>

                <h2 className="text-white">3. Payments and Subscriptions</h2>
                <p>
                  Nodes are subscribed to using Credits. Details on purchasing
                  Credits, subscription costs, and node deployment are available
                  on the platform&apos;s billing section.
                </p>
                <p>
                  All purchases are final and no refunds will be provided once
                  Credits are used for a subscription.
                </p>

                <h2 className="text-white">4. Rewards and Benefits</h2>
                <p>
                  Rewards generated by Nodes will be credited to users accounts
                  according to the specifics of each deployed Node.
                </p>
                <p>
                  Users are responsible for managing their accounts and rewards.
                  Detailed tracking of rewards is available through the user
                  dashboard.
                </p>

                <h2 className="text-white">5. User Responsibilities</h2>
                <p>
                  Users are responsible for maintaining the confidentiality of
                  their account information and for all activities under their
                  account.
                </p>
                <p>
                  You agree to comply with all local, state, national, and
                  international laws and regulations applicable to your use of
                  the Services.
                </p>
                <p>
                  <strong>Research Responsibilities:</strong> Each purchaser is
                  responsible for conducting their own research regarding the
                  network partners and the potential benefits and risks
                  associated with deploying Nodes on those networks.
                </p>

                <h2 className="text-white">6. Service Availability</h2>
                <p>
                  OpSec strives to ensure the availability and functionality of
                  the Services but does not guarantee uninterrupted service.
                  Maintenance and updates are necessary and can lead to
                  temporary unavailability.
                </p>

                <h2 className="text-white">7. Intellectual Property</h2>
                <p>
                  All content included on the platform, such as text, graphics,
                  logos, images, as well as the compilation thereof, and any
                  software used on the site, is the property of OpSec or its
                  suppliers and protected by copyright and intellectual property
                  laws.
                </p>

                <h2 className="text-white">8. Liability Limitation</h2>
                <p>
                  OpSec is not liable for any direct, indirect, incidental,
                  special, or consequential damages resulting from the use or
                  inability to use our services, including but not limited to
                  reliance by a user on any information obtained from the
                  service.
                </p>

                <h2 className="text-white">9. Dispute Resolution</h2>
                <p>
                  Any disputes related to these Terms will be handled through
                  arbitration under the rules of the jurisdiction agreed upon at
                  the time of dispute resolution.
                </p>

                <h2 className="text-white">10. Changes to Terms</h2>
                <p>
                  OpSec reserves the right to modify these Terms at any time. We
                  will notify users of any changes through our standard
                  communication channels. Continued use of the service after
                  such changes will constitute acknowledgment and agreement to
                  the modified terms.
                </p>

                <h2 className="text-white">11. Contact Information</h2>
                <p>
                  If you have any questions about these Terms, please contact us
                  via [insert contact method].
                </p>

                <h2 className="text-white">12. Termination</h2>
                <p>
                  OpSec may terminate your access to all or any part of the
                  Services at any time, with or without cause, with or without
                  notice, effective immediately.
                </p>

                <p>
                  <strong>
                    Appendix: Operational Insights and Strategic Directions
                  </strong>
                </p>
                <p>
                  This appendix summarizes key discussion points from internal
                  and external communications addressing several operational and
                  strategic aspects of our service:
                </p>
                <p>
                  <strong>Communication and Team Dynamics:</strong> Emphasizing
                  efficient onboarding, proper use of tagging in tickets for
                  prompt responses, and maintaining high standards in service
                  response times.
                </p>
                <p>
                  <strong>Financial and Legal Framework:</strong> Stresses the
                  importance of a robust refund policy and clear terms and
                  conditions to prevent brand reputation damage and manage
                  expectations effectively.
                </p>
                <p>
                  <strong>Technical Operations:</strong> Focus on addressing
                  node and wallet issues promptly, improving bug reporting
                  mechanisms, and maintaining technical integrity through
                  continuous updates.
                </p>
                <p>
                  <strong>Policy and Documentation:</strong> Commitment to
                  enhancing documentation clarity and ensuring ethical practices
                  in terms and conditions application.
                </p>
                <p>
                  <strong>Node Deployment and Transparency:</strong> Enhancing
                  the transparency of node operations and clarifying the
                  functionalities of different node types to set accurate user
                  expectations.
                </p>
                <p>
                  <strong>Customer Support:</strong> Implementing effective
                  ticket management systems and providing adequate support to
                  customer service staff to handle interactions competently.
                </p>
                <p>
                  <strong>Product Development:</strong> Ongoing product
                  development discussions aiming at integrating advanced
                  features like on-chain data and zk-proofs to enhance
                  transparency and user trust.
                </p>
                <p>
                  <strong>Telemetry and Tracking:</strong> Addressing
                  expectations versus reality in node tracking, emphasizing the
                  need for clear communication about operational realities, and
                  encouraging users to perform their own due diligence.
                </p>
                <p>
                  These points reflect our commitment to continuous improvement
                  and user satisfaction, guiding our operational strategies and
                  ensuring that we remain at the forefront of blockchain
                  technology services.
                </p>
              </div>
              <div className=" w-full  sticky bottom-[-20px] rounded-lg bg-blur backdrop-blur flex justify-end">
                <button
                  onClick={onAccept}
                  className="text-black bg-white rounded-lg px-4 py-2 m-2 hover:bg-green-600 hover:text-white"
                >
                  Accept Terms &amp; Conditions
                </button>
              </div>
            </div>
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  )
}

export default TermsAndConditions
