import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Providers } from "./providers"
import "@rainbow-me/rainbowkit/styles.css"
import "./globals.css"
import { Sidebar } from "@/components/sidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[url(/backgrounds/dashboard.png)] min-h-screen`}
      >
        <Providers>
          <main className="dark flex">
            <Sidebar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
