import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Providers } from "./providers"
import "@rainbow-me/rainbowkit/styles.css"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="dark flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
